<testsuite name="Mocha Tests" tests="3" failures="0" errors="1" skipped="0" timestamp="Tue, 31 May 2022 09:06:08 GMT" time="19.157">
<testcase classname="Givers Chain Transfers:Before swapAndLiquify is enabled" name="Should transfer with no fee for excluded accounts " time="0.2"/>
<testcase classname="Givers Chain Transfers:Before swapAndLiquify is enabled" name="Should transfer with fee for included accounts " time="0.016"><failure>overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault=&#x22;overflow&#x22;, operation=&#x22;BigNumber.from&#x22;, value=1.1579208923731618e+51, code=NUMERIC_FAULT, version=bignumber/5.6.2)
Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault=&#x22;overflow&#x22;, operation=&#x22;BigNumber.from&#x22;, value=1.1579208923731618e+51, code=NUMERIC_FAULT, version=bignumber/5.6.2)
    at Logger.makeError (node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
    at Logger.throwError (node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
    at throwFault (node_modules/@ethersproject/bignumber/src.ts/bignumber.ts:356:19)
    at Function.BigNumber.from (node_modules/@ethersproject/bignumber/src.ts/bignumber.ts:247:17)
    at toBN (node_modules/@ethersproject/bignumber/src.ts/bignumber.ts:345:27)
    at BigNumber.eq (node_modules/@ethersproject/bignumber/src.ts/bignumber.ts:155:30)
    at Proxy.&#x3C;anonymous&#x3E; (node_modules/@ethereum-waffle/chai/dist/cjs/matchers/bigNumber.js:33:72)
    at Proxy.overwritingMethodWrapper (node_modules/chai/lib/chai/utils/overwriteMethod.js:78:33)
    at Context.&#x3C;anonymous&#x3E; (test/Givers-test.js:101:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)</failure></testcase>
<testcase classname="Givers Chain Transfers:Before swapAndLiquify is enabled" name="Should not send fee to Charity and marketing wallet" time="0.078"/>
</testsuite>
